from __future__ import annotations

"""
Centralized default values for CLI, models, and settings.
Import these constants instead of repeating literals.
"""

# Topology/feature toggles
ENABLE_DEFAULT_OSPF6: bool = True
ENABLE_DEFAULT_ISIS: bool = False
ENABLE_DEFAULT_BGP: bool = False
ENABLE_DEFAULT_BFD: bool = False

# OSPFv3 defaults
OSPF_DEFAULT_HELLO_INTERVAL: int = 2
OSPF_DEFAULT_DEAD_INTERVAL: int = 10
OSPF_DEFAULT_SPF_DELAY_MS: int = 20
OSPF_DEFAULT_LSA_MIN_ARRIVAL_MS: int = 1000
OSPF_DEFAULT_MAXIMUM_PATHS: int = 1
OSPF_DEFAULT_RETRANSMIT_INTERVAL: int = 5
OSPF_DEFAULT_TRANSMIT_DELAY: int = 1
OSPF_DEFAULT_AREA_ID: str = "0.0.0.0"

# ISIS defaults
ISIS_DEFAULT_NET_ADDRESS: str = "49.0001.0000.0000.0001.00"
ISIS_DEFAULT_AREA_ID: str = "49.0001"
ISIS_DEFAULT_LEVEL_TYPE: str = "level-1"
ISIS_DEFAULT_METRIC_STYLE: str = "wide"

ISIS_DEFAULT_HELLO_INTERVAL: int = 3
ISIS_DEFAULT_HELLO_MULTIPLIER: int = 2
ISIS_DEFAULT_PRIORITY: int = 64

ISIS_DEFAULT_LSP_GEN_INTERVAL: int = 1
ISIS_DEFAULT_LSP_REFRESH_INTERVAL: int = 900
ISIS_DEFAULT_MAX_LSP_LIFETIME: int = 1200

ISIS_DEFAULT_SPF_INTERVAL: int = 2
ISIS_DEFAULT_SPF_INIT_DELAY_MS: int = 50
ISIS_DEFAULT_SPF_SHORT_DELAY_MS: int = 200
ISIS_DEFAULT_SPF_LONG_DELAY_MS: int = 5000
ISIS_DEFAULT_SPF_HOLDDOWN_MS: int = 800
ISIS_DEFAULT_SPF_TIME_TO_LEARN_MS: int = 5000

ISIS_DEFAULT_CSNP_INTERVAL: int = 10
ISIS_DEFAULT_PSNP_INTERVAL: int = 2

ISIS_DEFAULT_METRIC: int = 10
ISIS_DEFAULT_VERTICAL_METRIC: int = 10
ISIS_DEFAULT_HORIZONTAL_METRIC: int = 20
ISIS_DEFAULT_ENABLE_WIDE_METRICS: bool = True
ISIS_DEFAULT_THREE_WAY_HANDSHAKE: bool = True

# BGP defaults
BGP_DEFAULT_ASN: int = 65000

# BFD defaults
BFD_DEFAULT_ENABLED: bool = False
BFD_DEFAULT_DETECT_MULTIPLIER: int = 3
BFD_DEFAULT_INTERVAL_MS: int = 300
BFD_DEFAULT_PROFILE_NAME: str = "default"
BFD_DEFAULT_ECHO_MODE: bool = False
BFD_DEFAULT_ECHO_INTERVAL_MS: int = 50
BFD_DEFAULT_PASSIVE_MODE: bool = False
BFD_DEFAULT_MIN_TTL: int = 1

# App/Logging
DISABLE_LOGGING_DEFAULT: bool = False

# Mgmt defaults
MGMT_DEFAULT_EXTERNAL_ACCESS: bool = False

